apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: showroom-v2
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            appName: fiap-backend
            namespace: app
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: fiap-project
      source:
        repoURL: git@github.com:gabrielsilvao/fiap-fase3-app.git
        targetRevision: main
        path: k8s-manifests/
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true