apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-orders
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            appName: backend-orders
            namespace: orders
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: fiap-project
      source:
        repoURL: git@github.com:FIAP-Squad/backend-orders.git
        targetRevision: main
        path: manifests/
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true