apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fiap-project
spec:
  description: Project containing application
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false